### ISSUE TITLE
Feature Request: FULF Auto-Need on Unobtained/Unregistered items

### ISSUE THREAD

**Issue by GoblinGuide** [PunishXIV/LazyLoot#8]
This would be kind of the opposite of the "Pass on all items already unlocked." checkbox.

Use case: I'm grinding The Dead Ends during this mogtomes event for the minion. I have FULF set to auto-greed, for all the gear loot. I want to roll Need on the minion (if it ever drops.) without having to mess with FULF every time we hit the last boss.

Honestly, if this existed I'd leave it on 100% of the time. Not sure if I'm missing a function to do it that already exists?

**Comment by GoblinGuide** [comment]
...yeah, I just auto-greeded the TT cards/orch rolls/minion from the new alliance raid beacuse I was too stupid to remember to change FULF settings. Is there a reason this can't be done relatively simply?

**Comment by imgidedin** [comment]
You can just set it to need default and set to greed if the item for your
ilvl is 0 levels below if you want to only greed items.

Em sex., 6 de out. de 2023 13:39, GoblinGuide ***@***.***>
escreveu:

**Comment by GoblinGuide** [comment]
That worked just fine!

Second feature request: can we get an auto-pass list? If I'm running a party and don't want to lot on someone else's Thief's Maps but I want to make everything else move along quickly, for instance.
