### ISSUE TITLE
Crashing at end of duty

### ISSUE THREAD

**Issue by xKiisa** [PunishXIV/LazyLoot#9]
I have been doing 2 alliance raids and both times i crashed with LazyLoot enabled, only fix was to disable the plugin, otherwise it would keep me crashing when i load in. The log also shows LazyLoot so i assume something is wrong with it.

Kind regards <3

[dalamud_appcrash_20231012_192116_040_5148.log](https://github.com/PunishXIV/LazyLoot/files/12885442/dalamud_appcrash_20231012_192116_040_5148.log)

**Comment by drunknfairy** [comment]
Same issue. Tried a  few different duties and raids, always crashes at the end.

**Comment by imgidedin** [comment]
Can you guys give me some example of what you were running when it crashed? Because I`ve ran a lot of dungeons, raids and extremes trying to replicate this, without success.

**Comment by drunknfairy** [comment]
Dalamud appears saying it's crashing and gives some options including do you want to restart without plugins. I dont know where its logs are located

**Comment by imgidedin** [comment]
This problems seens to not be strictly related to LL, but a ClientStruct from Dalamud itself, that LL has to use. But again, what duty where you running when the crash happened? At what chest? Did it happened in a dungeon? What chest in said dungeon? We need data to test it out to find the possible culprit.

**Comment by drunknfairy** [comment]
For me it is very consistent (100%) in The Abyssal Fracture Extreme. The chest after beating the boss.

**Comment by imgidedin** [comment]
Thats weird. I did it like 50 times already, never crashed. Are you on running dalamud with the beta key?

**Comment by drunknfairy** [comment]
No, it is very vanilla. The only other Dalumud plugins I have running are Splatoon, Pandora's Box, LazyLoot, and Penumbra.  I disabled the other plugins and just ran LazyLoot and it crashes. I am running on a VPN and Advanced Combat Tracker is running also.

**Comment by imgidedin** [comment]
Could you try enabling the dalamud beta testing? Do you have an idea on how to do that? The key is `patella` and the kind is `stg`. Other than that, there is not much we can do, as this is completely not related to LL directly, it is something that LL has to use for it to work.

**Comment by drunknfairy** [comment]
I do have the "Get Plugin Testing Builds" box checked on the experimental tab, but if it is something else I do not see the option in Dalumud. Could you provide instructions please? Thank you.

**Comment by imgidedin** [comment]
Open this file with a text editor `%appdata%\XIVLauncher\dalamudConfig.json`
Change `"DalamudBetaKey": null,` to `"DalamudBetaKey": "patella",` and `"DalamudBetaKind": null,` to `"DalamudBetaKind": "stg",`. Then, restart the game and dalamud.

**Comment by xKiisa** [comment]
The alliance raids it crashed me in were The Labyrinth of the Ancients and World of Darkness. I'm on the stable branch right now but i can try the stg for testing

**Comment by xKiisa** [comment]
Crashed again in Labyrinth of the Ancients while on the stg branch

**Comment by Evernow** [comment]
I can also reproduce this crashing at the end of the arr alliance raids

**Comment by olee** [comment]
This happens to me always when there are faded orchestrion rolls in the loot.
Lazy loot rolls until it reaches those and exactly then crashes.

**Comment by xKiisa** [comment]
I personally haven't encountered another crash since the last update
